In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('super_messy_eda_dataset.csv')
df

,customer_id,order_id,age,gender,city,product_category,price,quantity,discount_percent,order_date,payment_method,customer_rating,delivery_days,returned
0,1171,363,21,NaN,Hyderabad,Sports,1912.09,three,0,2021-02-23,NetBanking,NaN,14,Y
1,1047,496,33,NaN,Mumbai,Electronics,268.35,4,20,2021-09-02,COD,?,10,Y
2,1185,206,42,Female,NaN,Sports,230.39,1,10,2022-07-10,NaN,2,4,Y
3,1135,113,54,NaN,Delhi,Electronics,1615.11,5,0,2022-05-18,Card,NaN,12,Yes
4,1092,311,45,M,Pune,Electronics,461.19,two,0,2023-08-31,upi,five,3,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645,1095,259,NaN,F,NaN,Sports,NaN,4,25%,2024-02-23,UPI,2,14,No
646,1016,362,49,M,Chennai,Electronics,NaN,three,25%,2023-09-05,NaN,NaN,12,Y
647,1025,409,20,Female,Unknown,Toys,1186.9,three,25%,2023-07-15,card,five,4,No
648,1150,396,73,M,Unknown,Grocery,925.72,NaN,25%,2023-12-23,NetBanking,?,2,N
649,1194,256,NaN,Female,Kolkata,Toys,1424.66,NaN,NaN,2022-01-06,card,1,4,Y

In [3]:
df.head()

,customer_id,order_id,age,gender,city,product_category,price,quantity,discount_percent,order_date,payment_method,customer_rating,delivery_days,returned
0,1171,363,21,NaN,Hyderabad,Sports,1912.09,three,0,2021-02-23,NetBanking,NaN,14,Y
1,1047,496,33,NaN,Mumbai,Electronics,268.35,4,20,2021-09-02,COD,?,10,Y
2,1185,206,42,Female,NaN,Sports,230.39,1,10,2022-07-10,NaN,2,4,Y
3,1135,113,54,NaN,Delhi,Electronics,1615.11,5,0,2022-05-18,Card,NaN,12,Yes
4,1092,311,45,M,Pune,Electronics,461.19,two,0,2023-08-31,upi,five,3,No

In [4]:
df.shape

(650, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       650 non-null    int64
 1   order_id          650 non-null    int64
 2   age               582 non-null    object
 3   gender            500 non-null    object
 4   city              532 non-null    object
 5   product_category  650 non-null    object
 6   price             597 non-null    object
 7   quantity          530 non-null    object
 8   discount_percent  541 non-null    object
 9   order_date        650 non-null    object
 10  payment_method    584 non-null    object
 11  customer_rating   520 non-null    object
 12  delivery_days     604 non-null    object
 13  returned          514 non-null    object
dtypes: int64(2), object(12)
memory usage: 71.2+ KB

In [6]:
df.describe(include="all")

,customer_id,order_id,age,gender,city,product_category,price,quantity,discount_percent,order_date,payment_method,customer_rating,delivery_days,returned
count,650.000000,650.000000,582,500,532,650,597,530,541,650,584,520,604,514
unique,NaN,NaN,61,7,9,7,350,7,8,495,7,7,16,4
top,NaN,NaN,43,Female,Pune,Beauty,197.13,1,10%,2024-06-14,card,5,10,No
freq,NaN,NaN,17,77,72,110,6,95,78,5,94,90,49,135
mean,1101.709231,297.332308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,57.309799,173.347413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1000.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1052.000000,147.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1102.000000,295.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1150.000000,449.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1199.000000,600.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.columns

Index(['customer_id', 'order_id', 'age', 'gender', 'city', 'product_category',
       'price', 'quantity', 'discount_percent', 'order_date', 'payment_method',
       'customer_rating', 'delivery_days', 'returned'],
      dtype='object')

In [8]:
df.columns = df.columns.str.lower()

In [9]:
df.columns

Index(['customer_id', 'order_id', 'age', 'gender', 'city', 'product_category',
       'price', 'quantity', 'discount_percent', 'order_date', 'payment_method',
       'customer_rating', 'delivery_days', 'returned'],
      dtype='object')

In [10]:
# replaceing missing values
df.replace(["?","Unknown","unknown","not_available",""], np.nan, inplace = True)

In [11]:
# Remove Duplicates
df.duplicated().sum()

np.int64(50)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
# clean gender column
df["gender"] = df["gender"].replace({
    "M":"Male",
    "F":"Female",
    "male":"Male",
    "female":"Female"
})
df["gender"] = df["gender"].fillna(df["gender"].mode()[0])

In [15]:
df["gender"]

0        Male
1        Male
2      Female
3        Male
4        Male
        ...
644    Female
645    Female
646      Male
648      Male
649    Female
Name: gender, Length: 600, dtype: object

In [16]:
# clean city column
df["city"] = df["city"].str.strip()
df["city"] = df["city"].fillna(df["city"].mode()[0])

In [17]:
df["city"]

0      Hyderabad
1         Mumbai
2           Pune
3          Delhi
4           Pune
         ...
644         Pune
645         Pune
646      Chennai
648         Pune
649      Kolkata
Name: city, Length: 600, dtype: object

In [18]:
# clean age column
df["age"] = pd.to_numeric(df["age"], errors = "coerce")

In [19]:
df["age"]

0      21.0
1      33.0
2      42.0
3      54.0
4      45.0
       ...
644    47.0
645     NaN
646    49.0
648    73.0
649     NaN
Name: age, Length: 600, dtype: float64

In [20]:
df["age"] = df["age"].fillna(df["age"].median())

In [21]:
df["age"] = df["age"].astype(int)
df["age"]

0      21
1      33
2      42
3      54
4      45
       ..
644    47
645    45
646    49
648    73
649    45
Name: age, Length: 600, dtype: int64

In [24]:
# clean price column

df["price"] = df["price"].astype(str)

df["price"] = df["price"].str.replace(",", "")

df["price"] = df["price"].str.replace("free", "0")

df["price"] = pd.to_numeric(df["price"], errors="coerce")

df["price"] = df["price"].fillna(df["price"].mean())

In [25]:
df["price"]

0      1912.090000
1       268.350000
2       230.390000
3      1615.110000
4       461.190000
          ...
644     518.430000
645    1274.447403
646    1274.447403
648     925.720000
649    1424.660000
Name: price, Length: 600, dtype: float64

In [49]:
# clean quantity column
df["quantity"] = df["quantity"].replace({
    "two":2,
    "three":3
})
df["quantity"] = df["quantity"].fillna(df["quantity"].mode()[0])

In [50]:
df["quantity"] = df["quantity"].astype(int)

In [51]:
df["quantity"]

0      3
1      4
2      1
3      5
4      2
      ..
644    1
645    4
646    3
648    3
649    3
Name: quantity, Length: 600, dtype: int64

In [52]:
# clean discount column
df["discount_percent"] = df["discount_percent"].astype(str)
df["discount_percent"] = df["discount_percent"].replace("%","")
df["discount_percent"] = pd.to_numeric(df["discount_percent"], errors = "coerce")
df["discount_percent"] = df["discount_percent"].fillna(0)

In [53]:
df["discount_percent"]

0       0
1      20
2      10
3       0
4       0
       ..
644    20
645     0
646     0
648     0
649     0
Name: discount_percent, Length: 600, dtype: int64

In [54]:
df["discount_percent"] = df["discount_percent"].astype(int)

In [55]:
df["discount_percent"]

0       0
1      20
2      10
3       0
4       0
       ..
644    20
645     0
646     0
648     0
649     0
Name: discount_percent, Length: 600, dtype: int64

In [56]:
# Clean Date Column
df["order_date"] = pd.to_datetime(df["order_date"], errors = "coerce")
df["order_date"] = df['order_date'].fillna(method='ffill')

C:\Users\Shree\AppData\Local\Temp\ipykernel_10504\2772888110.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["order_date"] = df['order_date'].fillna(method='ffill')

In [57]:
df["order_date"]

0     2021-02-23
1     2021-09-02
2     2022-07-10
3     2022-05-18
4     2023-08-31
         ...
644   2024-08-15
645   2024-02-23
646   2023-09-05
648   2023-12-23
649   2022-01-06
Name: order_date, Length: 600, dtype: datetime64[ns]

In [58]:
# Clean Payment Method column
df["payment_method"] = df["payment_method"].replace({
    "upi":"UPI",
    "card":"Card"
})
df["payment_method"] = df["payment_method"].fillna(df["payment_method"].mode()[0])

In [59]:
df["payment_method"]

0      NetBanking
1             COD
2            Card
3            Card
4             UPI
          ...
644           COD
645           UPI
646          Card
648    NetBanking
649          Card
Name: payment_method, Length: 600, dtype: object

In [64]:
# clean customer rating column
df["customer_rating"] = df["customer_rating"].replace({
    "five":5,
    "?":""
})
df["customer_rating"] = pd.to_numeric(df["customer_rating"], errors = "coerce")

In [65]:
df["customer_rating"] = df["customer_rating"].fillna(df["customer_rating"].mean())

In [67]:
df["customer_rating"] = df["customer_rating"].astype(int)

In [68]:
df["customer_rating"]

0      3
1      3
2      2
3      3
4      5
      ..
644    3
645    2
646    3
648    3
649    1
Name: customer_rating, Length: 600, dtype: int64

In [69]:
# Clean Delivery Days column
df["delivery_days"] = df["delivery_days"].replace({
    "?":"",
    "unknown":""
})

In [70]:
df["delivery_days"]

0      14
1      10
2       4
3      12
4       3
       ..
644     8
645    14
646    12
648     2
649     4
Name: delivery_days, Length: 600, dtype: object

In [72]:
df["delivery_days"] = pd.to_numeric(df["delivery_days"], errors = "coerce")
df["delivery_days"] = df["delivery_days"].fillna(df["delivery_days"].mean())

In [74]:
df["delivery_days"] = df["delivery_days"].astype(int)

In [75]:
df["delivery_days"]

0      14
1      10
2       4
3      12
4       3
       ..
644     8
645    14
646    12
648     2
649     4
Name: delivery_days, Length: 600, dtype: int64

In [77]:
# Clean Returned Column
df["returned"] = df["returned"].replace({
    "Y":"Yes",
    "N":"No"
})
df["returned"] = df["returned"].fillna(df["returned"].mode()[0])

In [78]:
df["returned"]

0      Yes
1      Yes
2      Yes
3      Yes
4       No
      ...
644     No
645     No
646    Yes
648     No
649    Yes
Name: returned, Length: 600, dtype: object

In [80]:
# Handle Outliers (IQR Method)
numeric_cols = df.select_dtypes(include = ["int64","float64"]).columns

In [83]:
for cols in numeric_cols:
    Q1 = df[cols].quantile(0.25)
    Q3 = df[cols].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[cols] = np.where(df[cols] < lower, lower, df[cols])
    df[cols] = np.where(df[cols] > upper, upper, df[cols])

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 600 entries, 0 to 649
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       600 non-null    float64
 1   order_id          600 non-null    float64
 2   age               600 non-null    float64
 3   gender            600 non-null    object
 4   city              600 non-null    object
 5   product_category  600 non-null    object
 6   price             600 non-null    float64
 7   quantity          600 non-null    float64
 8   discount_percent  600 non-null    float64
 9   order_date        600 non-null    datetime64[ns]
 10  payment_method    600 non-null    object
 11  customer_rating   600 non-null    float64
 12  delivery_days     600 non-null    float64
 13  returned          600 non-null    object
dtypes: datetime64[ns](1), float64(8), object(5)
memory usage: 70.3+ KB

In [85]:
df.isnull().sum()

customer_id         0
order_id            0
age                 0
gender              0
city                0
product_category    0
price               0
quantity            0
discount_percent    0
order_date          0
payment_method      0
customer_rating     0
delivery_days       0
returned            0
dtype: int64

In [86]:
df.to_csv("cleaned_e-commerce_dataset.csv",index=False)